//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 07:37:15 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://de.mondry/questionnaire/beans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.mondry.questionnaire.parse.beans;
