//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.14 at 07:39:44 PM CET 
//

package de.mondry.questionnaire.parse.beans;

import java.util.UUID;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for question complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="question">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="question" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="answerlist" type="{http://de.mondry/questionnaire/beans}answerlist"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "question", propOrder = { "question", "answerlist" })
public class Question {
    
    @XmlElement(required = true)
    protected String question;
    @XmlElement(required = true)
    protected Answerlist answerlist;
    private transient UUID id;
    
    public UUID getId() {
        return id;
    }
    
    /**
     * Gets the value of the question property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getQuestion() {
        return question;
    }
    
    /**
     * Sets the value of the question property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setQuestion(String value) {
        this.question = value;
    }
    
    /**
     * Gets the value of the answerlist property.
     * 
     * @return possible object is {@link Answerlist }
     * 
     */
    public Answerlist getAnswerlist() {
        return answerlist;
    }
    
    /**
     * Sets the value of the answerlist property.
     * 
     * @param value
     *            allowed object is {@link Answerlist }
     * 
     */
    public void setAnswerlist(Answerlist value) {
        this.answerlist = value;
    }
    
    @Override
    public String toString() {
        return "Question [question=" + question + ", answerlist=" + answerlist + "]";
    }
    
    public void setId(UUID randomUUID) {
        this.id = randomUUID;
        
    }
    
}
