//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 02:55:53 PM CET 
//


package de.mondry.questionnaire.parse.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for question complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="question">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="questionString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="answerlist" type="{http://de.mondry/questionnaire/beans}answerlist"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "question", propOrder = {
    "questionString",
    "answerlist"
})
public class Question {

    @XmlElement(required = true)
    protected String questionString;
    @XmlElement(required = true)
    protected Answerlist answerlist;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the questionString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionString() {
        return questionString;
    }

    /**
     * Sets the value of the questionString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionString(String value) {
        this.questionString = value;
    }

    /**
     * Gets the value of the answerlist property.
     * 
     * @return
     *     possible object is
     *     {@link Answerlist }
     *     
     */
    public Answerlist getAnswerlist() {
        return answerlist;
    }

    /**
     * Sets the value of the answerlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Answerlist }
     *     
     */
    public void setAnswerlist(Answerlist value) {
        this.answerlist = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
